### ISSUE TITLE
why the number of label is much less than the training samples?

### ISSUE THREAD

**Issue by ShihuaiXu** [Jai-Shankar-K-N/Skyfinder#1]
There is only one mask file in the official website, could please tell me the reason of it? Thank you in advance.

**Comment by Jai-Shankar-K-N** [comment]
This Dataset is a smaller version of the original SkyFinder dataset by Mihail, This dataset contains A COLLECTION of images  of a single location that are taken over different weather conditions.since the location is same for varied weather conditions the mask for it remains the same.so u have one mask per location.

**Comment by ShihuaiXu** [comment]
thank you very much, could I download the original SkyFinder dataset by Mihail, would you like tell me how to download it? Thank you in advance.

**Comment by Jai-Shankar-K-N** [comment]
It is possible using webscraping method and the csv files. The whole dataset contains around 90k images. I wouldn't personally prefer it as loading the whole dataset and training a model is a time consuming task and requires very high computational power

**Comment by ShihuaiXu** [comment]
Thank you very much, I use this githup link to download the data, but the speed is always 0
https://github.com/vivekverma1019/sky_segmentation
Do you know the reason?

**Comment by ShihuaiXu** [comment]
do you have the baidu cloud disk? I am trying to download the dataset in githup, but it always failed

**Comment by Jai-Shankar-K-N** [comment]
I was busy, in the mean time i have a gift for u.


import bs4,requests,os
if not os.path.isdir('Sky'):
  os.mkdir('Sky')
  os.mkdir('Sky/Dataset')
  os.mkdir('Sky/groundtruth')
page=requests.get('https://mypages.valdosta.edu/rpmihail/skyfinder/images/')
pageobj=bs4.BeautifulSoup(page.text)
anchors=pageobj.select('a')
for i in anchors:
  j=i.get('href')
  if j.endswith('zip'):
    data=requests.get('https://mypages.valdosta.edu/rpmihail/skyfinder/images/'+j,allow_redirects=True)
    open('Sky/Dataset/'+j, 'wb').write(data.content)
  elif j.endswith('png'):
    data=requests.get('https://mypages.valdosta.edu/rpmihail/skyfinder/Masks'+j.split('/')[-1],allow_redirects=True)
    open('Sky/groundtruth/'+j.split('/')[-1], 'wb').write(data.content)
  else:  
    continue




WEBSCRAPING CODE FOR SKYFINDER DATASET
once it is complete, unzip all the files in the Dataset folder and u are ready.

**Comment by Jai-Shankar-K-N** [comment]
I was busy, in the mean time i have a gift for u.

import bs4,requests,os
if not os.path.isdir('Sky'):
    os.mkdir('Sky')
    os.mkdir('Sky/Dataset')
    os.mkdir('Sky/groundtruth')
page=requests.get('https://mypages.valdosta.edu/rpmihail/skyfinder/images/')
pageobj=bs4.BeautifulSoup(page.text)
anchors=pageobj.select('a')
for i in anchors:
    j=i.get('href')
    if j.endswith('zip'):
        data=requests.get('https://mypages.valdosta.edu/rpmihail/skyfinder/images/'+j,allow_redirects=True)
        open('Sky/Dataset/'+j, 'wb').write(data.content)
    elif j.endswith('png'):
        data=requests.get('https://mypages.valdosta.edu/rpmihail/skyfinder/Masks'+j.split('/')[-1],allow_redirects=True)
        open('Sky/groundtruth/'+j.split('/')[-1], 'wb').write(data.content)
    else:
        continue

WEBSCRAPING CODE FOR SKYFINDER DATASET
once it is complete, unzip all the zip files in the Dataset folder and u are ready

**Comment by Jai-Shankar-K-N** [comment]
![scrape](https://user-images.githubusercontent.com/60354084/87309408-323f3680-c53a-11ea-9992-c1938d2c67eb.png)
use this code to download the Skyfinder dataset and unzip all the zip files in the Dataset folder
